### ISSUE TITLE
ENAMETOOLONG error on install on linux again

### ISSUE THREAD

**Issue by teoric** [brunnerh/insert-unicode#33]
Installing 0.13.0 fails due to long file name, looks like #26 again.

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. Install the 0.13.0, either from file or from update button.

```
[2021-09-28 09:56:52.384] [renderer1] [error] ENAMETOOLONG: name too long, open '/home/XXX/.vscode/extensions/.b30f4dc6-e7bd-4eba-9a3a-9227f5530b17/out/commands/node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.js': extracting: ENAMETOOLONG: name too long, open '/home/XXX/.vscode/extensions/.b30f4dc6-e7bd-4eba-9a3a-9227f5530b17/out/commands/node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.js'
    at f.extractAtLocation (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:185479)
    at async f.extractUserExtension (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:182453)
    at async F.extract (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:194886)
    at async F.doRun (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195589)
```

**Expected behavior**

install the new version

**Environment (please complete the following information):**
 - OS: Linux amd64
 - Visual Studio Code Version: 1.60.2
 - Extension Version: 0.13.0

**Comment by brunnerh** [comment]
Sorry about that. It looks like some debug build files got published accidentally.

Should add a pre-build step that cleans up first to ensure that this cannot happen.

**Comment by brunnerh** [comment]
Should be fixed in v.0.13.1 and automatically be prevented in the future.

**Comment by teoric** [comment]
Great, thank you for that fast fix!
